### ISSUE TITLE
Not able to get the app running

### ISSUE THREAD

**Issue by yunanwg** [rqi14/Perplexica-docker#1]
First, thanks for the idea of creating this project, could definitely make life easier!

**Describe the bug**

After running docker compose up, I can get access to the application behind reverse proxy, but it stuck at loading screen. 

The containes logs report no error.

In browser console, I saw that:

```
GET https://<masked_internal_frontend_domain>/discover?_rsc=acgkz 404 (Not Found)
```

as well as

```
GET https://<masked_internal_frontend_domain>/__NEXT_PUBLIC_API_URL__/models 404 (Not Found)
```

**To Reproduce**

The `app.dockerfile` and `config.toml` remains untouched.

My `docker-compose.yaml`:

```yaml
services:
  frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_WS_URL=ws://backend:3001/ws
        - NEXT_PUBLIC_API_URL=http://backend:3001/api
    container_name: perplexica-frontend
    restart: unless-stopped
    expose:
      - 3000
    depends_on:
      - backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.perplexica.rule=Host(`${SUBDOMAIN}.${INTERNAL_DOMAIN}`)
      - traefik.http.routers.perplexica.entrypoints=websecure
      - traefik.http.routers.perplexica.tls.certresolver=step-ca

  backend:
    image: rqi14/perplexica-app:slim
    container_name: perplexica-backend
    restart: unless-stopped
    expose:
      - 3001
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - data:/home/perplexica/data
      - ./config.toml:/home/perplexica/config.toml
    labels:
      - traefik.enable=true
      - traefik.http.routers.perplexica-backend.rule=Host(`${BACKEND_SUBDOMAIN}.${INTERNAL_DOMAIN}`)
      - traefik.http.routers.perplexica-backend.entrypoints=websecure
      - traefik.http.routers.perplexica-backend.tls.certresolver=step-ca

networks:
  default:
    name: traefik
    external: true

volumes:
  data:
```

**Expected behavior**

**Screenshots**

**Additional context**
